server:
  port: 3344
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://git@github.com/fei178/springcloud-config.git
          search-paths: config-repo
          username: fei178   #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          password: MMnn1314  #密码